[package]
name = "jack-midiswitch"
version = "0.1.0"
authors = ["Florian Jung <flo@windfis.ch>"]
edition = "2018"
license = "BSD-2-Clause"

[dependencies]
jack = { git = "https://github.com/Windfisch/rust-jack" }
ringbuf = "0.2.1"
clap = "2"
